export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_CANCEL = 'EDIT_TASK_CANCEL';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
